- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: sleep 10 sec
      - shell: sleep 10
    - name: Hello Again
      debug: 
        msg: "Hello World Again!"
